# docker-compose development override for hydrant service
---
version: "3.4"
services:
  hydrant:
    command: sh -c "flask run --host 0.0.0.0 --port ${PORT:-9000}"
    environment:
      FLASK_ENV: development
    volumes:
    # set in .env
      - "${HYDRANT_CHECKOUT_DIR}/:/opt/app"
